/**:
  ros__parameters:
    # Format: [x1, y1, x2, y2, ...]
    waypoints:
      # --- Straight Away ---
      - 0.0
      - 0.0
      - 10.0
      - 0.0
      - 20.0
      - 0.0
      
      # --- Large 10m Radius Turn (Clockwise) ---
      - 27.07
      - 2.93
      - 30.0
      - 10.0
      - 27.07
      - 17.07
      
      # --- Straight Back ---
      - 20.0
      - 20.0
      - 10.0
      - 20.0
      - 0.0
      - 20.0
      
      # --- Turn back to Start ---
      - -7.07
      - 17.07
      - -10.0
      - 10.0
      - -7.07
      - 2.93
      
      # --- Origin ---
      - 0.0
      - 0.0